apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  labels:
    app: client

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    
    spec:
      containers:
      - name: client-container
        image: abhi0874/job-tracker-frontend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80